// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: GetFeedFollowsForUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT feeds.name, users.name AS user_name FROM feed_follows
INNER JOIN feeds ON feed_follows.feed_id = feeds.id 
INNER JOIN users ON feed_follows.user_id = users.id
WHERE users.id = $1
`

type GetFeedFollowsForUserRow struct {
	Name     string
	UserName string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, id uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(&i.Name, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
