// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const resetf = `-- name: Resetf :exec
DELETE FROM feeds
`

func (q *Queries) Resetf(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetf)
	return err
}

const resetfollow = `-- name: Resetfollow :exec
DELETE FROM feed_follows
`

func (q *Queries) Resetfollow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetfollow)
	return err
}

const resetu = `-- name: Resetu :exec
DELETE FROM users
`

func (q *Queries) Resetu(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetu)
	return err
}
